### ISSUE TITLE
Text Annotations not getting saved in Playground

### ISSUE THREAD

**Issue by C130187** [diffgram/diffgram#1069]
https://user-images.githubusercontent.com/14860314/192012312-38b97e86-f03c-43af-964d-b6b84d242f79.mp4

**Comment by vitalii-bulyzhyn** [comment]
Hey @C130187 !

Thanks for pointing this out, we already working on this

**Comment by vitalii-bulyzhyn** [comment]
@C130187 [here](https://www.loom.com/share/17da3c4125e7498fb799988d7048a8dd) is small demo on how it works

**Comment by anthony-sarkis** [comment]
@C130187   In the video provided it shows as "saved". Maybe there is an issue with that specific file type or something else. 
May you share the dev console logs (errors, or failed http requests) please so we can review further?

@vitalii-bulyzhyn  Given above maybe this is a different issue. Otherwise UI expectation wise we may want to reconsider this since at least as shown in video it appears saved

**Comment by PJEstrada** [comment]
Fixed on [release `1.8.](https://github.com/diffgram/diffgram/releases/tag/1.8.17)

**Comment by anthony-sarkis** [comment]
Thanks @PJEstrada and @vitalii-bulyzhyn
