### ISSUE TITLE
Text annotations not getting exported on playground

### ISSUE THREAD

**Issue by C130187** [diffgram/diffgram#1078]
https://user-images.githubusercontent.com/14860314/193159780-7a344003-be94-41af-ae7f-01c4096fa139.mp4

**Comment by anthony-sarkis** [comment]
Each annotation is saved as an "Instance".
I understand it's confusing that there are the tokens and the empty tag, but that information is provided as a convenience and is not the annotations.
The annotations are in the instance list. So in your video it appears to be correctly showing them at the end of the video. Each instance is one annotation. Since in your case each annotation was only one token the start and end token numbers are the same. 
It's on our todo list to make this format more clear since of course there's a lot of extra not useful information like for image cases etc. 
Please advise if that makes sense?

![image (31)](https://user-images.githubusercontent.com/18080164/193160504-d568fc95-8bb9-41f4-b5fe-925b2855ce37.png)

**Comment by anthony-sarkis** [comment]
@vitalii-bulyzhyn 
Not to disrupt any current items, but just as something to put on your radar for future: 
When we build the export dict in the text case we can just include text related fields?
As a temporary thing I added the following to the text section https://diffgram.readme.io/docs/text-annotation-guide#5-export-the-data 
but also not sure if there's the best place to make the text export format really clear.
![image](https://user-images.githubusercontent.com/18080164/193160922-85d87bd0-b556-4992-a59b-c21630c28fef.png)
