### ISSUE TITLE
UI Schema bug?

### ISSUE THREAD

**Issue by feifeizuo** [diffgram/diffgram#1231]
Hi,
        I use White-label Customization create a custom ui schema(remove some elements).
       Then I create a task and set the custom ui schema to it.
       But when I click START ANNOTATING button, the page is blank.

**Comment by anthony-sarkis** [comment]
@feifeizuo may you send a video or screenshot please? 
are there any console messages?

**Comment by feifeizuo** [comment]
Please view this video. [Download Link](https://www.jianguoyun.com/p/DeydegoQtuigBxjn5-kEIAA) Thanks.

**Comment by feifeizuo** [comment]
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/6001243/204743255-dac4677a-a643-4760-b9fb-2aa7f1180e56.png">

**Comment by anthony-sarkis** [comment]
Thank you. Exactly what is needed. We will review

**Comment by anthony-sarkis** [comment]
@feifeizuo 
So each of those items, is likely something that gets removed by UI schema.
This is an area we don't have great test coverage for yet, because as features change on the UI, they work like normal, but then UI schema changes the context.

The fix is actually pretty easy, so each of those console messages, basically just needs a null check to not fire if the element isn't present. (e.g. hidden by UI schema).  Basically adding an undefined check in each of those functions 

Our team is at capacity at the moment with existing tasks, so offhand this wouldn't be a priority.
If you can submit a pull request for it we would greatly appreciate it! 

PS
If you haven't already joined our slack channel that's another way we can help engage on dev questions with you or your team :)
