### ISSUE TITLE
Clarify existing test setup

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1510]
`"test:unit": "vue-cli-service test:unit --silent",`

* what value `vue-cli-service` is providing
* plan because `vue-cli-service`  is in mode
* why `yarn jest` appears to yield difference results (*Expected since otherwise why use `vue-cli-service` but want to understand it a bit better, and also odd that it appeared to have historically worked)

**Comment by sergzak022** [comment]
- "what value vue-cli-service is providing" -> from the [documentation](https://cli.vuejs.org/core-plugins/unit-jest.html#injected-commands) page. "Note that directly running jest will fail because the Babel preset requires hints to make your code work in Node.js, so you must run your tests with vue-cli-service test:unit."
- "plan because vue-cli-service is in mode" -> It looks like we can get rid of `@vue/cli-plugin-unit-jest` and change `test:unit` `package.json` script from `"vue-cli-service test:unit --silent"` to just `yarn jest`. This because `jest.config.js` has all the required transformers for vue and ts configured.
- "why yarn jest appears to yield difference results" -> once I reverted dependencies back to the "original" versions (see [here](https://github.com/diffgram/diffgram/pull/1511/files#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655)), I get the same result when run `yarn jest`
