### ISSUE TITLE
Request for Comments (RFC) on DLv2 and Diffgram Contributor License (CL)

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#1543]
We are requesting comments on the new DLv2 and Diffgram Contributor License (CL)

Here's the latest preview of DLv2:
https://diffgram.readme.io/docs/diffgram-license-v2-dlv2

As part of this change introducing the new Diffgram Contributor License (CL)
https://diffgram.readme.io/docs/diffgram-contributor-license-cl

**Comment by francescov1** [comment]
Looks great so far! Couple questions/comments:

DLv2
- Where does the 25M figure come from? Do we have an idea on % increase of the addressable market?
- 25M in yearly revenue is drastically different from 25M in funding, we may want to separate these two figures.
- I'd state Definitions near the top to provide proper context for the rest of the doc
- Does the MSA already exist somewhere? Was looking for it in docs but couldnt find it

CL
- `1 Major Pull Request (PR) (~120+ hours of engineering work)` seems like way too much work for a single PR. I understand we want to be flexible with the open-source community but don't think we should incentivize developers to pack that much work in a single PR.
- Have we considered setting a # of diffs requirement instead of an hourly requirement? Ultimately the volume of code contributed matters more than the number of hours, and can't be faked at all
  - Where does the 120h come from? Has this been a typical amount of work that contributors have done in the past?

**Comment by sergzak022** [comment]
Diffgram License v2 (DLv2) Preview looks good to me. $25M annual revenue seems like a reasonable amount. It does seem like "Definitions" section should be moved closer to the top, but I'm not a lawyer so not sure if you're following some standard there.

The Contribution Requirements in the CL are quite clear and seem to promote sustained, substantial involvement from contributors, which is great to see. However, it might be beneficial to have a bit more guidance on distinguishing between major, medium, and small pull requests to help companies plan their contributions better. May be in makes sense to use a combination of hours and # of diffs requirement somehow. Are there any existing license documents for some other open source projects that you're using for inspiration?

**Comment by anthony-sarkis** [comment]
Thanks everyone! 

Updated both links.
https://diffgram.readme.io/docs/diffgram-contributor-license-cl
https://diffgram.readme.io/docs/diffgram-license-v2-dlv2

- Reframed the Contribution requirement to be about the spirit of the contribution, with three recommended options including an option for lines of code diffs.
- Updated to be under $25M funding or $5M revenue. Generally above that it's better for companies to engage with us under a MSA or CL.
- The Definitions section style (and the original version of this) is inspired by [ELv2](https://www.elastic.co/licensing/elastic-license). I think most of the concern here is ease of reading the most key points, and most of the definitions should be non-controversial so may be better to keep them near the bottom. Moved some of the terms like `USD` to definitions so `1.` can read as smoothly and clearly as possible.
- [Added msa overview ](https://diffgram.readme.io/docs/master-services-agreement-msa)
- Generally reframed the contributor license page, including clearly stating "Diffgram MSA customers will receive a financial credit for all contributions."
