### ISSUE TITLE
Provide an example .env file for docker-compose.yml please.

### ISSUE THREAD

**Issue by fishfree** [diffgram/diffgram#1569]
Many thanks!

**Comment by sergzak022** [comment]
Hey @fishfree , what are you trying to do? Does this [docker-compose.yml](https://github.com/diffgram/diffgram/blob/master/docker-compose.yaml) work?

**Comment by fishfree** [comment]
@sergzak022 Thank you! I just want to use that YAML, but there is no correspondent .env or env.example file.

**Comment by anthony-sarkis** [comment]
@fishfree Please see docs here for docker https://diffgram.readme.io/docs/install
It steps through everything needed and will automatically generate the env file and performs some self checks.

Or if doing an engineering level install see -> https://diffgram.readme.io/docs/new-engineer-welcome#diffgram-env-variables
> To create this .env file use the install.py script to set up your env variables. This will generate the .env file with the values. The file should be placed in your diffgram directory. To learn more about general concepts see [Secrets](https://diffgram.readme.io/docs/secrets).

Currently, the install.py is the canonical way to generate the env file (an empty .env file is intentionally not provided.). This is due to potential confusion around configuration and need for generation of unique secrets. For more details see above linked docs. Always open to improvements in any of this, just describing current state.

**Comment by fishfree** [comment]
@anthony-sarkis Thank you! It turned out the .env file is generated by running python install.py.
