### ISSUE TITLE
Support Merging Of Polygons

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#219]
In some cases objects can be separated and need to be annotated with 2 disjoint polygons, we should support being able to "merge" them into a single instances since the object is just one in this case.

**Comment by PJEstrada** [comment]
Some ideas to keep in mind:

- Do we present this as a single instance? If so maybe we need to change the polygon representation to be a list of points lists instead of a single list?
- Maybe adding the concept of a parent_instance? This can create a lot more complextity overall in the system but is an option.
- Add an additional key to the x,y keys so that we can have something like {x:4,y: 78 polygon_num}, {x:1,y:2,_polygon_num:2}, etc

**Comment by anthony-sarkis** [comment]
The single instance idea feels like the easiest to implement because it's  just "more spatial information". Making it seems to be the most well scoped to this specific need.

#### From UI perspective: 
a user could select an existing polygon and do some action  (hotkey, button etc) to "add more spatial shapes" or something.  Then it enters a drawing mode where it populates that data. 

#### Selecting:
any spatial aspect of the shape selects that one instance, so that action should be similar. 

#### Editing:
points may need extra work since to know which "subshape", and may be some oddities there to consider.

From a technical view, the key could not exist (or exist with null value) for most cases and then exist when needed. 

I feel like there could be some edge cases here but probably the fastest path to reasonable resolution on this one. :)
