### ISSUE TITLE
Local storage support

### ISSUE THREAD

**Issue by scotthuang1989** [diffgram/diffgram#33]
Diffgram only support clould storage?

**Comment by PJEstrada** [comment]
Hi @scotthuang1989! Yes, for now Diffgram only supports cloud storage. Let us now if you are interested in us supporting local storage, we might be able to support it soon! :)

**Comment by anthony-sarkis** [comment]
Started a thread on this here: https://github.com/diffgram/diffgram/discussions/38

**Comment by JeancarloBarrios** [comment]
A good workaround will be to use MinIO [minion link](https://min.io/). MinIO’s high-performance, Kubernetes-native object storage. However, you can install it using docker or Minikube on your local machine. It works with the AWS s3 SDK(it has full parity); therefore, you can use it as a drop-in replacement for S3 with full compatibility.

**Comment by scotthuang1989** [comment]
@PJEstrada  sorry for the late response; I am working on some small personal project (I work on it in my personal time, so efficiency is very important), I think diffgram can solve some problem for me.

**Comment by meyerjo** [comment]
Any update regarding that topic? Do you have it on the agenda to support different/locally hosted storage solutions?

**Comment by PJEstrada** [comment]
Hi @meyerjo,

We don't have a plan to release this feature in the short term. Maybe on Q2/Q3 we can have V1. We would be interested though in understanding how would you like this support to be presented? What types of file systems do you use?

Right now sounds like MinIO is the easiest way to set this up but I would be interested in your thoughts on it

**Comment by meyerjo** [comment]
Sorry just saw the notification. 
It would be nice to either be able to run it locally on a normal filesystem or on a computer/server with a mounted NFS4 filesystem.

I once briefly tried MinIO but didn't really had success in configuring it. Should it already work or would it (just) be the easiest way to extend diffgram?

**Comment by anthony-sarkis** [comment]
A couple thoughts here

1) The storage needs to be accessible to the client. 
Not saying this is "hard" but just a consideration if using a purely local file system.

2) Using a local file system we would need to evaluate scalability aspect. If for nothing else but to understand the performance relative to cloud systems so as to better to inform users. e.g. can a local only storage system work for 10M object? 100M?

3) An HDFS type system may be another option

In terms of implementation, we have control on where we write/read files. Already patterns for multiple storage providers etc.

@towr @meyerjo  
1) Any specific use cases you can share?
2) Any intent drivers you can share? (Cost, security, control, etc.?)

**Comment by towr** [comment]
My first use case would be a hassle-free trial. If I can simply install it, and everything works out of the box, then I can try out the features and see if it suits my needs (and possibly my company's).  At the moment I first need to arrange cloud storage somehow.

The second use case would be personal usage. If I want to use it for my personal projects, I would want to run it on my desktop without needing costly external infrastructure. Scalability would not be a consideration there.

If (when selected at install) MinIO could be automatically added to the docker-compose file and configured, I think that would be a great option for both use-cases. But that's going a step further than just adding it as a storage option. I suspect local storage would be simpler (since configuration-wise it only requires mounting a volume in docker-compose).

**Comment by meyerjo** [comment]
I think most of @towr points are also valid for me. 
I would add data privacy. It would be great to be able to run Diffgram internally (in my case university) and not to have to upload the collected data to one of the big ones. If everything is processed on my machines no additional approvement steps are required, otherwise it is just too complicated. (In addition approvement for the financial cost for storing data "abroad" would be required)

**Comment by anthony-sarkis** [comment]
Thanks everyone! We for sure need to add local storage options. We have a
lot on our plate right now so I'm not sure when we'll be able to get to
this but it's definitely something we need to do.

**Comment by anthony-sarkis** [comment]
Great news!! Local storage is here with MinIO!!

https://github.com/diffgram/diffgram/releases/tag/0.15.0

https://github.com/diffgram/diffgram/pull/857

(For now auto adding minio has been left to future ticket
https://github.com/diffgram/diffgram/issues/862, but as long as minio is installed should be good to go!)

@meyerjo @towr @scotthuang1989 @JeancarloBarrios
