### ISSUE TITLE
Image compression on using facing media

### ISSUE THREAD

**Issue by anthony-sarkis** [diffgram/diffgram#596]
Continuing the discussion from https://github.com/diffgram/diffgram/pull/593

To summarize some of the above:
1) We currently store the raw files as part of ingestion process. So the the assumption when creating any new modified artifacts is they are for specific purpose. For example for human UI centric use. The user or other processes can decide to pull the raw or modified image.
2) In the context of 1) we may as well focus on space efficient storage options, e.g. for network transfer speed to user etc. For example defaulting to JPG and even a specific value on imwrite like 95

To add another reason why we do the raw storage, is that it helps decouple the processing layer from the raw ingestion layer. So for example as long as we can stream the raw bytes to the server we can ingest as much as we want. And if we have say a 30GB video file that needs to retry processing we can do that too.

This discussion is generally focused on images, but can also apply to other media formats.
Video -> We assume the new artifact will be .mp4 

Current state (to be verified)
Assuming this is already happening with imwrite default settings if input is jpg already
Assuming this is not happening if the input type is `png`

**Comment by MathijsNL** [comment]
In my opinion having the facing media just as a copy of the raw media would be the best option (by default). When using userscripts you want them to use the original unaltered file, and not a lower quality one in the case of lossy formats.

For lossless formats my concern is processing power. Bandwith and storage are relatively cheap, but if someone wants to upload 10.000 already optimized PNG images (say compress_level=8) this would take a long time to process, because the imageio.imwrite function for PNG defaults to compression level 9 (best compression but slowest). I think in case someone forgets to optimize their PNG this is going to be beneficial, but if someone already has heavily optimized PNG images we will only make them bigger if we select a lower compress_level.

The table below gives some file size results, starting with no compression (0) and ending with highest compression (9).

| compress_level| Time | Filesize  |Percentage|
|---|---|---|---|
|0|0.07|7047.2kB|100.0| 
|1|0.14|2238.1kB|31.8| 
|2|0.17|2169.2kB|30.8| 
|3|0.24|2037.3kB|28.9| 
|4|0.23|1896.8kB|26.9| 
|5|0.45|1851.0kB|26.3| 
|6|0.75|1804.9kB|25.6| 
|7|1.21|1782.1kB|25.3| 
|8|4.52|1726.0kB|24.5| 
|9|9.30|1700.9kB|24.1| 

What we could do is calculate the compression level of a file, and if it is above a threshold, say 50%, the facing media gets written to a new file with compress_level=4 for example. Otherwise the original media gets used.

Let me know your thoughts.

**Comment by MathijsNL** [comment]
Yes it actually is. I haven't found out if the actual compression level is stored in the file, but the calculation is simple and fast.
file_size / (image_width * image_height * image_depth * image_channels) = compression ratio.

There is 1 problem though, and that is that not every PNG file has the same characteristics.

I did some more testing with a PNG with Perlin noise. Those results are wildly different.
![image](https://user-images.githubusercontent.com/1612886/154127262-ad5d29f3-f007-42af-b7db-812bd8203c6f.png)

| Compression  | Time | Filesize  |Percentage|
|---|---|---|---|
|0|0.12|7047.2kB|100.0| 
|1|0.27|5214.3kB|74.0| 
|2|0.27|5213.7kB|74.0| 
|3|0.27|5213.7kB|74.0| 
|4|0.35|4929.9kB|70.0| 
|5|0.32|4929.9kB|70.0| 
|6|0.46|4929.9kB|70.0| 
|7|0.47|4929.9kB|70.0| 
|8|0.36|4929.9kB|70.0| 
|9|0.33|4929.9kB|70.0| 

Both the compression (bad, to be expected) but also the amount of time being used. It just gives up faster if it can't compress good enough.

Maybe the best approach would be to pick compress_level=2, compare the file size and pick the smallest one? This is getting kind of complicated because there isn't a one size fits all solution.

If the main focus is scale, then it might even be better to not apply compression at all or to do that client side.

@PJEstrada What are your thoughts after this update?

**Comment by MathijsNL** [comment]
It seems to be that the compression header can be found easier in the file itself than on the internet.

https://stackoverflow.com/questions/9050260/what-does-a-zlib-header-look-like


|Level | ZLIB   | DESCRIPTION |
|---|---|---|
|  0   | 78 01 |superfast|
|  1   | 78 01 |superfast|
|  2   | 78 5E |fast|
|  3   | 78 5E |fast|
|  4   | 78 5E |fast|
|  5   | 78 5E |fast|
|  6   | 78 9C |default|
|  7   | 78 DA |maximum|
|  8   | 78 DA |maximum|
|  9   | 78 DA |maximum|

So this means reading byte 63 from the file and comparing it with the ZLIB compression level number will give the current compression level.

Considering the marginal gains on anything over fast compression I think checking if superfast compression was used, and if so apply fast compression at compress_level=2.

Because of the relatively complex code to determine the compression level an easier way is to see if level 0 was used (by calculating the ratio (width * height * channels) / filesize, and in that case only apply compress_level=2 to the file, because the difference between level 0 and 1 is already pretty big.
