### ISSUE TITLE
Add option to disable imageSmoothing

### ISSUE THREAD

**Issue by MathijsNL** [diffgram/diffgram#670]
I ran some tests with maximum file size upload, and I noticed that if you zoom in really far that the image looks blurry.

To visualize this I created an image with random pixels.

![image](https://user-images.githubusercontent.com/1612886/155442450-51eef77e-3221-4410-b177-c39341644e00.png)
Note: Comparison images are not the same scale! The data explorer is 6 pixels in height for reference.

It is really hard to see individual pixels. I haven't found the cause for this behavior yet.

**Comment by anthony-sarkis** [comment]
My current understanding:

By default canvas smoothes the image
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled

For quick context, a little while back it was all the rage to turn it `false` to see the pixelated "true" representation.
And then I think people realized that for most cases it's just nicer to look at the smoothed image, and since ultimately it snaps to the pixel boundaries anyway the result in theory should be the same. 

It's just that one flag to turn it off, so we could make this an option pretty easily probably.
In my option the default should be blurred still unless there's strong evidence otherwise.

We could also explore the quality setting
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality

If it's publicly shareable, I'd be curious if you have a specific use case in mind for seeing the pixels?

**Comment by MathijsNL** [comment]
Hey Anthony,

The specific usecase is whenever you have dark objects, and there is a shade it starts to become harder to see where the actual border is. In all cases where contrast is good it shouldn't matter too much. When contrast is bad I think it is best to present the data as accurately as possible.

Here is an example.

Original:
![image](https://user-images.githubusercontent.com/1612886/155510123-870623e0-53d5-4174-a421-1ad809ee19f9.png)



Data Explorer:
![image](https://user-images.githubusercontent.com/1612886/155509548-00770fed-58c1-407f-8c85-adad24e2719c.png)


Data explorer (increased brightness):
![image](https://user-images.githubusercontent.com/1612886/155510618-a33ed6f4-6afe-4e91-8061-2f53bcd29087.png)

When I open the original image on my PC I can clearly see the line that should be followed, on Diffgram it is harder.

**Comment by anthony-sarkis** [comment]
@MathijsNL  Thank you very much - that all makes sense.

Yes that's a good place, I added this https://github.com/diffgram/diffgram/pull/676
Please let me know your thoughts

**Comment by MathijsNL** [comment]
@anthony-sarkis Yes that looks great! Thanks for adding this.

**Comment by anthony-sarkis** [comment]
Pleasure!  Once Pablo reviews it we can merge :)
