### ISSUE TITLE
Docker error on installing development with remote Postgress SQL

### ISSUE THREAD

**Issue by amrlafi** [diffgram/diffgram#69]
> Launching Diffgram...
WARNING: The CLOUD_STORAGE_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The ML__CLOUD_STORAGE_BUCKET variable is not set. Defaulting to a blank string.
WARNING: The DIFFGRAM_AWS_ACCESS_KEY_ID variable is not set. Defaulting to a blank string.
WARNING: The DIFFGRAM_AWS_ACCESS_KEY_SECRET variable is not set. Defaulting to a blank string.
WARNING: The DIFFGRAM_S3_BUCKET_NAME variable is not set. Defaulting to a blank string.
WARNING: The ML__DIFFGRAM_S3_BUCKET_NAME variable is not set. Defaulting to a blank string.
WARNING: The MAILGUN_KEY variable is not set. Defaulting to a blank string.
Docker Compose is now in the Docker CLI, try `docker compose up`
Pulling db (scratch:)...
**ERROR: 'scratch' is a reserved name**
Diffgram Successfully Launched!
View the Web UI at: http://localhost:8085

The install.py script also ignores the error and assumes launching was successful.

**Comment by PJEstrada** [comment]
Hi @amrlafi  

Thanks for sharing this one :) This a prolbem with docker adding scratch as a reserved name in their newest versions: https://github.com/moby/moby/issues/10737

When you set the installation with a remote PSQL endpoint we create this 'scratch' image as a dummy image. We will work on removing this dummy image name and use another one. Probably we will change it to: https://registry.hub.docker.com/r/tianon/true . I'll link the PR when the fix is ready.

In the meanwhile as a workaround you could try changing the `POSTGRES_IMAGE` inside generated `.env` by the install script to `tianon/true`.

**Comment by amrlafi** [comment]
Thanks for your reply. 
I can also suggest an improvement to the install script: The script should test the provided connection string "connection test."
The first time I provided a wrong connection string and the **default** docker image allows shut down due to this error.
