### ISSUE TITLE
Labels Schema V1

### ISSUE THREAD

**Issue by PJEstrada** [diffgram/diffgram#787]

**Comment by anthony-sarkis** [comment]
### Schema V1  Draft
## Intent

- Make it easier conceptually to work with multiple groups of labels in the same project
- Group labels, attributes, and templates into “Schema”

### Why

- The relationship between Projects, Labels and Tasks is slightly foggy right now. If it was clear that a Task uses a Schema, and a Project has multiple of either, that would conceptually be more clear.
- When importing from external parties that have multiple Schema
- It’s an ease of use concern that cross cuts all media types.
- This would make it faster to reuse Schema ABC on multiple tasks (select Schema A vs [list] of labels) 
- to actually create pipelines with multiple stages more clearly (e.g. stage 1 has Schema A, stage 2 has Schema B), 
- to better complete work within the scope of a single project (even an expert user right now has to mentally remember which assets are for which making the reuse argument not as strong).
- Unlocks large volumes of labels, since right now it would be difficult to do anything but “select all”
- Ensures value of other features, like the Feature Store / Query concepts. Since any major projects are likely to have multiple Schemas.
- As we grow volume of interfaces this also may further become relevant, if someone had multiple data types in the same project they are bound to have different sets of labels

**Future**
- Potentially helps with analytics and “what to label” concerns / model review, if we can filter by specific Schemas.
- Having this as a named concept will unlock future ideas around business value and product features.

**Comment by PJEstrada** [comment]
Thanks Anthony!
